- op: replace
  path: /metadata/name
  value: emojdbtest
- op: replace
  path: /spec/source/path
  value: deployment/plat-app-services/emojdbtest
- op: replace
  path: /spec/project
  value: plat-app-services