apiVersion: v1
kind: PersistentVolume
metadata:
  name: emoj-frontend-pv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: emoj-frontend-pvc
  hostPath:
    path: "/media/marco/emoj/backend/video"
    type: DirectoryOrCreate


