apiVersion: v1
kind: Service
metadata:
  labels:
    app: emoj-db
  name: emoj-db-svc
spec:
  ports:
  # PostgreSQL wire protocol clients.
  - port: 3306
    targetPort: 3306
    name: mysql
  selector:
    app: emoj-db

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: emoj-db-deployment
  labels:
    app: emoj-db
  annotations:
    # Tell Reloader to bounce the Argo CD server whenever the SSO config
    # and built-in admin credentials change.
    secret.reloader.stakater.com/reload: "postgres-users"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emoj-db
  template:
    metadata:
      labels:
        app: emoj-db
    spec:
      containers:
      - name: mysql
        image: "mysql:5.6"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: "MYSQL_ROOT_PASSWORD"
          value: "test1234"
        volumeMounts:
        - name: emoj-db-pvc
          mountPath: /var/lib/mysql
      volumes:
      - name: emoj-db-pvc
        persistentVolumeClaim:
          claimName: emoj-db-pvc
