apiVersion: v1
kind: Service
metadata:
  labels:
    app: emoj-frontend
  name: emoj-frontend-svc
spec:
  ports:
  - name: http
    port: 4200
    protocol: TCP
    targetPort: 4200
  selector:
    app: emoj-frontend

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: emoj-frontend
  name: emoj-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emoj-frontend
  template:
    metadata:
      labels:
        app: emoj-frontend
    spec:
      initContainers:
        - name: emojdbfrontendinit
          image: $ACCOUNT.dkr.ecr.$REGION.amazonaws.com/kitt4sme-db-init:latest
          imagePullPolicy: IfNotPresent
          env:
          - name: ACCOUNT
            valueFrom:
              secretKeyRef:
                name: emoj-secret
                key: aws.account
          - name: REGION
            valueFrom:
              secretKeyRef:
                name: emoj-secret
                key: aws.region
          - name: POSTGRES_HOST
            value: "emoj-db"
          - name: POSTGRES_PORT
            value: "5432"
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: emoj-secret
                key: postgreshego.password
          - name: POSTGRES_INITPASSWORD
            valueFrom:
              secretKeyRef:
                name: emoj-secret
                key: postgresemoj.password
      containers:
        - image: $ACCOUNT.dkr.ecr.$REGION.amazonaws.com/kitt4sme-dashboard:latest
          imagePullPolicy: IfNotPresent
          name: emoj-frontend
          ports:
          - containerPort: 4200
            name: http
          env:
          - name: ACCOUNT
            valueFrom:
              secretKeyRef:
                name: emoj-secret
                key: aws.account
          - name: REGION
            valueFrom:
              secretKeyRef:
                name: emoj-secret
                key: aws.region
          - name: EMOJ_BACKEND
            value: "http://emoj-backend:5000"
          - name: POSTGRES_HOST
            value: "emoj-db"
          - name: POSTGRES_PORT
            value: "5432"
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: emoj-secret
                key: postgreshego.password
          - name: VIDEO_PATH
            value: "/app/videos"
          volumeMounts:
            - mountPath: /app/videos
              name: emoj-frontend-pvc
      volumes:
        - name: emoj-frontend-pvc
          persistentVolumeClaim:
            claimName: emoj-frontend-pvc
