apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: emoj-backend
spec:
  accessModes: 
  - ReadWriteOnce
  resources: 
    requests: 
      storage: 1Gi
  storageClassName: ""
  volumeName: emoj-db-pv

