apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: emoj-frontend-pvc
  namespace: emoj
spec:
  accessModes: 
  - ReadWriteOnce
  resources: 
    requests: 
      storage: 10Gi
  storageClassName: ""
  volumeName: emoj-frontend-pv

