apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: emoj-db-pvc
spec:
  accessModes: 
  - ReadWriteOnce
  resources: 
    requests: 
      storage: 1Gi
  storageClassName: ""
  volumeClaim: emoj-db-pv

