apiVersion: v1
kind: Service
metadata:
  labels:
    app: emoj-frontend
  name: emoj-frontend-svc
spec:
  ports:
  - name: http
    port: 4200
    protocol: TCP
    targetPort: 4200
  selector:
    app: emoj-frontend

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: emoj-frontend
  name: emoj-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emoj-frontend
  template:
    metadata:
      labels:
        app: emoj-frontend
    spec:
      initContainers:
        - name: emojdbfrontendinit
          image: emojdbinit:latest
          imagePullPolicy: IfNotPresent
          env:
          - name: POSTGRES_HOST
            value: "emoj-db"
          - name: POSTGRES_PORT
            value: "5432"
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-emoj
                key: postgreshego.password
          - name: POSTGRES_INITPASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-emoj
                key: postgresemoj.password
      containers:
        - image: emojimagefrontend:latest
          imagePullPolicy: IfNotPresent
          name: emoj-frontend
          ports:
          - containerPort: 4200
            name: http
          env:
          - name: EMOJ_BACKEND
            value: "emoj-backend-svc"
          - name: POSTGRES_HOST
            value: "emoj-db"
          - name: POSTGRES_PORT
            value: "5432"
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-emoj
                key: postgreshego.password
      volumes:
        - name: emoj-frontend-pvc
          persistentVolumeClaim:
            claimName: emoj-frontend-pvc
