apiVersion: v1
kind: Service
metadata:
  labels:
    app: emoj-db
  name: emoj-db-svc
spec:
  ports:
  # PostgreSQL wire protocol clients.
  - port: 5432
    targetPort: 5432
    name: postgres
  selector:
    app: emoj-db

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: emoj-db-deployment
  labels:
    app: emoj-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emoj-db
  template:
    metadata:
      labels:
        app: emoj-db
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: POSTGRES_USER
          value: "POSTGRES_USER"
        - name: POSTGRES_PASSWORD
          value: "test123"
        - name: POSTGRES_DB
          value: "hego_dashboard"
        volumeMounts:
        - name: emoj-db-pvc
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: emoj-db-pvc
        persistentVolumeClaim:
          claimName: emoj-db-pvc
