apiVersion: v1
kind: Service
metadata:
  labels:
    app: emoj-frontend
  name: emoj-frontend-svc
spec:
  ports:
  - name: http
    port: 4200
    protocol: TCP
    targetPort: 4200
  selector:
    app: emoj-frontend

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: emoj-frontend
  name: emoj-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emoj-frontend
  template:
    metadata:
      labels:
        app: emoj-frontend
    spec:
      containers:
        - image: emojimagefrontend:latest
          imagePullPolicy: IfNotPresent
          name: emoj-frontend
          ports:
          - containerPort: 4200
            name: http
          env:
          - name: POSTGRES_HOST
            value: "emoj-db-svc"
          - name: POSTGRES_PORT
            value: "5432"
          - name: POSTGRES_USER
            value: "POSTGRES_USER"
          - name: POSTGRES_PASSWORD
            value: "test123"
          - name: POSTGRES_DB
            value: "hego_dashboard"
      volumes:
        - name: emoj-frontend-pvc
          persistentVolumeClaim:
            claimName: emoj-frontend-pvc
