apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-builtin-admin
  namespace: default
spec:
  encryptedData:
    password: AgBtfiPzIbUnEPLMemoG+q48WBiSBMEznrGGaVIidYycEh97mQ2M0xIbK6MxAy0oQIa706vah4/V1zlWiLyuKWl1GBCYZPG1VV4Trbl7e2JKmCnTNXxGHR3Jwlw/Bq+WsJDictOlG5PNcDb8aKxRXEGg4QVpx7nw5EZufD4fzIca8w5wc/xCCvWGvaWu1a8jHfN7iBqzS4cAzj9hOVRaTrNFo1R9tgEBNy4I/5OsWxzxenRAn9pKmoAi1nhmPRaYN0H5oi26THu1De++vXrUL+gp3w542CPUn1QT8cGxX2dtkTOFoY8G7NYqwT4b58Vus/81S1Fa2BsHq/eLk+85FIl5KST7YRBT8ibcyoM/JoNEMsyZY3pei5PNUlPttdQMwaeLxtOHTQ2dh6llHxbbsz+RJKsDqSmGsYOqUf/6121zwIlPEu9ynAwmwuxmxGbzkuRzLP2C+S16+fRvuxzYfNJeciaUZT0U8RpkahJ+MJQbdE319l07PM8hfSKicHEO6R4i9z4vJNLSgaYh+uZwF68ShbGo3zsy2bNUKx+6A06pwPJFgL0vsNLuQRaim8uvz2SImupydx92FXAA+bY8NNzi3tkWyV/gz8EAhVrEuiQJlZfVt//LrPcb6FfcIYW5JTHyQKym9ZlI950R4AqS5Q+JyL4ynDCmRvh19FTcPa1226ulrhwdXtZlZ0OFqgygyn4OCmWvozswrcWxvEGLdFNqzeI6gg==
    username: AgDJYAUDL5Q+HyzqwvnC2zT+1Va/CHGm34acY13fiSQSOry+4iepRbwlpLYgoZ2BCx7fy7tkr2tnDGczOWWW75raChG2d56HK6lkPA/Nazez61+XvXkeTTLchNsiC1W530CjXExssVwrPR9zoCkXE7c/lcx3RsNbPWZUwGWgbZ12u95MLHv6ATqnVxy+2HDKRlJorIYMqjsx1Fdbi22bmw/dpdQblp0S9vdd5VzG2A2TAZg0JtRefGqUC0MvNHhrUhPfu8oI74cZ2QNsomENd4YVUHEdWx5I5CZ5dvvwAauCcky9CIAjCjBxASa46GED7qjHb9txqgAuKw5eaimZH2ojImL3/HSa9nzbz2icxnmMqnWAky5QAjGVDhsiivyd3il/ePxJ8Dqb9U56EjoKVxHnLlxtEkkM9XpDzpNAMqUcZTBh0hO6ZxgPhtvmoximHwzUf7l+LqVXYVgog8hXE6bP8N8TffvySqtA11Rhl/3EE3ah4gqabNCBgFeB/J0yQjIgAII20cHqOrO9JnWw3ZkFz5F/mqZFz0cTWztp6HKlWqQWlfbYtbOEwdM9MQn+BmfZs69fHk0FiowsnVfxlgL3Tpisq9Q9pjol+5MGQQgEG3rbvKPD1A8cEbEbb+M+LfwTCTjwKWAb+VRbr+PB+7mQDiSV+QusjmPRZtL2W7eU6h9kuAPOogKJR0fCE0dXeuGiyK4J8A==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: keycloak-builtin-admin
      namespace: default
    type: Opaque

